[versions]
okhttp = "4.12.0"
disklrucache = "2.0.2"

[libraries]
disklrucache = { module = "com.jakewharton:disklrucache", version.ref = "disklrucache" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

